### ISSUE TITLE
Komplettering laboration 3

### ISSUE THREAD

**Issue by 1dv449** [me222wm/1dv449_laboration3#1]
Komplettera med en rubrik om Web sockets i din reflektion och beskriv vad webbsockets är och kort hur de fungerar. 

Svara här när du är klar.

**Comment by me222wm** [comment]
[Här](https://github.com/me222wm/1dv449_laboration3/blob/master/README.md#vad-är-websockets-komplettering) har jag kort beskrivit web sockets.

**Comment by 1dv449** [comment]
OK
